/motion_capture_tracking:
  ros__parameters:
    # one of "optitrack", "optitrack_closed_source", "vicon", "qualisys", "nokov", "vrpn", "motionanalysis"
    type: "qualisys"

    # Specify the hostname or IP of the computer running the motion capture software
    hostname: "10.24.5.189"

    # Specify additional settings for the /poses topic here
    topics:
      poses:
        qos:
          mode: "none" # one of "none" or "sensor"
          deadline: 100.0 # Hz
